#!/bin/sh

# Copyright (C) 1998-2004 Linux Canada Inc.  All rights reserved.
#
# This file is part of Quasar Accounting
#
# This file may be distributed and/or modified under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation and appearing in the file LICENSE.GPL included in the
# packaging of this file.
#
# Licensees holding a valid Quasar Commercial License may use this file
# in accordance with the Quasar Commercial License Agreement provided
# with the Software in the LICENSE.COMMERCIAL file.
#
# This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
# WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
# See http://www.linuxcanada.com or email sales@linuxcanada.com for
# information about Quasar Accounting support and maintenance options.
#
# Contact sales@linuxcanada.com if any conditions of this licensing are
# not clear to you.

FILE=$1
BUILD_DIR=~/quasar_rpm

# Build directory structure
if [ ! -d $BUILD_DIR ]; then
    mkdir $BUILD_DIR
    mkdir $BUILD_DIR/BUILD
    mkdir $BUILD_DIR/RPMS
    mkdir $BUILD_DIR/SOURCES
    mkdir $BUILD_DIR/SPECS
    mkdir $BUILD_DIR/SRPMS
    mkdir $BUILD_DIR/RPMS/athlon
    mkdir $BUILD_DIR/RPMS/i386
    mkdir $BUILD_DIR/RPMS/i486
    mkdir $BUILD_DIR/RPMS/i586
    mkdir $BUILD_DIR/RPMS/i686
    mkdir $BUILD_DIR/RPMS/noarch
fi

# Setup exported directory contents
echo "Copying Quasar source code..."
cp -f $FILE $BUILD_DIR/SOURCES
tar -xOzf $FILE "*/quasar.spec" >$BUILD_DIR/SPECS/quasar.spec

# Build the RPM's
echo -e "Building the rpm files..."
cd $BUILD_DIR/SPECS
rpmbuild --define "_topdir $BUILD_DIR" -ba quasar.spec
